exports['default'] = {
  routes: function(api){
    return {
        get: [
            {path: '/locations/provinces', action: 'provinces'},
            {path: '/locations/province/:id', action: 'province'},
            {path: '/locations/cities/:pid', action: 'cities'},
            {path: '/locations/city/:id', action: 'city'},
            {path: '/locations/regions/:cid', action: 'regions'},
            {path: '/locations/region/:id', action: 'region'},
            {path: '/account', action: 'account:check'},
            {path: '/account/view', action: 'account:view'},
            {path: '/user-management', action: 'user-management:list'},
            {path: '/vehicle-management', action: 'vehicle-management:list'},
            {path: '/module-management',action:'module-management:list'},
            {path: '/material-management',action:'material-management:list'},
            {path: '/module-group-management',action:'module-group-management:list'},
            {path: '/seat-group-management',action:'seat-group-management:list'},
            {path: '/getAllGroupTitles',action:'module-group-management:getAllGroupTitles'},
            {path: '/organization-management',action:'organization-management:list'},
            {path: '/role-management',action:'role-management:list'},
            {path: '/task-management',action:'task-management:list'},
            {path: '/customer-management',action:'customer-management:list'},
            {path: '/waybill-management',action:'waybill-management:list'},
            {path: '/waybill-management/settlementList',action:'waybillSettlement-management:list'},
            {path: '/alliance-management',action:'alliance-management:list'},
            {path: '/user-management/:id', action: 'user-management:view'},
            {path: '/vehicle-management/:id', action: 'vehicle-management:view'},
            {path: '/module-management/:id', action: 'module-management:view'},
            {path: '/material-management/:id', action: 'material-management:view'},
            {path: '/module-group-management/:id',action:'module-group-management:view'},
            {path: '/seat-group-management/:id',action:'seat-group-management:view'},
            {path: '/organization-management/:id',action:'organization-management:view'},
            {path: '/role-management/:id',action:'role-management:view'},
            {path: '/task-management/:id',action:'task-management:view'},
            {path: '/customer-management/:id',action:'customer-management:view'},
            {path: '/docs', action: 'showDocumentation'},
            {path: '/status', action: 'status'},
            {path: '/account', action: 'session:check'},
            {path: '/isNotExist', action: 'isNotExist:check'},
            {path: '/user-module', action: 'userModule:list'},
            {path: '/user-module/selected', action: 'userModule:selected'},
            {path: '/user-material/byUserId', action: 'user-material:byUserId'},
            {path: '/material/one', action: 'material:view'},
            {path: '/verifyUser', action: 'verify:user'},
            {path: '/waybill-management/see',action:'waybillAckImg-management:view'},
            {path: '/waybill-management/edit',action:'waybill-management:view'},
            {path: '/waybill-management/view',action:'waybillPayment-management:view'},
            {path: '/financial-management',action:'financial-management:list'},
            {path: '/financial-management/:id',action:'financial-management:view'},
            {path: '/TaskDispatchOffer-management',action:'TaskDispatchOffer-management:getOfferedVehicles'},
            {path: '/alliance-management/:id',action:'alliance-management:view'},
            {path: 'waybill-management/compensationView',action:'waybillCompensation-management:view'},
        ],
        post: [
            {path: '/session', action: 'session:create'},
            {path: '/account', action: 'account:create'},
            {path: '/user-management', action: 'user-management:create'},
            {path: '/vehicle-management', action: 'vehicle-management:create'},
            {path: '/module-management', action: 'module-management:create'},
            {path: '/material-management', action: 'material-management:create'},
            {path: '/user-module', action: 'userModule:save'},
            {path: '/user-material/save', action: 'user-material:save'},
            {path: '/module-material/save', action: 'module-material:save'},
            {path: '/material-material/save', action: 'material-material:save'},
            {path: '/module-group-management', action: 'module-group-management:create'},
            {path: '/seat-group-management', action: 'seat-group-management:create'},
            {path: '/organization-management', action: 'organization-management:create'},
            {path: '/role-management', action: 'role-management:create'},
            {path: '/task-management', action: 'task-management:create'},
            {path: '/taskDispatch-management', action: 'taskDispatch-management:create'},
            {path: '/customer-management', action: 'customer-management:create'},
            {path: '/sendMessage', action: 'verify:generate'},
            {path: '/waybill-management/upload', action: 'waybillAckImg-management:upload'},
            {path: '/waybill-management', action: 'waybillPayment-management:payment'},
            {path: '/waybill-management/save', action: 'waybill-management:create'},
            {path: '/waybill-management/compensation', action: 'waybillCompensation-management:compensation'},
            {path: '/waybill-management/termination', action: 'waybillTermination-management:termination'},
            {path: '/waybill-management/settlement', action: 'waybillSettlement-management:settlement'},
            {path: '/alliance-management',action:'alliance-management:create'},
        ],
        put: [
            {path: '/session', action: 'session:check'},
            {path: '/account', action: 'account:edit'},
            {path: '/user-management', action: 'user-management:edit'},
            {path: '/vehicle-management', action: 'vehicle-management:edit'},
            {path: '/module-management', action: 'module-management:edit'},
            {path: '/material-management', action: 'material-management:edit'},
            {path: '/module-group-management', action: 'module-group-management:edit'},
            {path: '/seat-group-management', action: 'seat-group-management:edit'},
            {path: '/organization-management', action: 'organization-management:edit'},
            {path: '/role-management', action: 'role-management:edit'},
            {path: '/task-management', action: 'task-management:edit'},
            {path: '/customer-management', action: 'customer-management:edit'},
            {path: '/waybill-management', action: 'waybill-management:edit'},
            {path: '/waybill-management/paymentEdit', action: 'waybill-management:paymentEdit'},
            {path: '/financial-management', action: 'financial-management:edit'},
            {path: 'taskDispatchOffer-management',action: 'taskDispatchOffer-management:edit'},
            {path: '/alliance-management',action:'alliance-management:edit'},
        ],

        delete: [
            {path: '/session', action: 'session:destroy'},
            {path: '/registry', action: 'registry:destroy'},
            {path: '/user-management/:id', action: 'user-management:delete'},
            {path: '/vehicle-management/:id', action: 'vehicle-management:delete'},
            {path: '/module-management/:id', action: 'module-management:delete'},
            {path: '/material-management/:id', action: 'material-management:delete'},
            {path: '/module-group-management/:id', action: 'module-group-management:delete'},
            {path: '/seat-group-management/:id', action: 'seat-group-management:delete'},
            {path: '/organization-management/:id', action: 'organization-management:delete'},
            {path: '/role-management/:id', action: 'role-management:delete'},
            {path: '/task-management/:id', action: 'task-management:delete'},
            {path: '/customer-management/:id', action: 'customer-management:delete'},
            {path: '/alliance-management/:id',action:'alliance-management:delete'},
        ],
    };
  }
};
